### ISSUE TITLE
Trouble getting main.php to run -- won't connect to neo4j

### ISSUE THREAD

**Issue by imnotstiller** [in3rsha/bitcoin-to-neo4j#16]
Hello, 

I went through the instructions, and I believe I have redis and neo4j up (I set the user and password) and edited the config.php to find the blockchain. It looks like I am not able to connect with neo4j thru the start script (see below) and I am getting the errors below. 

Any help would be very much appreciated!

```
$ php main.php
define("BLOCKS", '/scr1/bitcoin/blocks'); // the location of the blk.dat files you want to read
define("TESTNET", false); // are you reading blk.dat files from Bitcoin's testnet?

define("NEO4J_USER", 'neo4j');
define("NEO4J_PASS", 'neo4j');    
define("NEO4J_IP", 'localhost');
define("NEO4J_PORT", '7687'); // this is the port used for the bolt protocol

define("REDIS_IP", 'localhost');
define("REDIS_PORT", '6379');
PHP Warning:  Use of undefined constant REDIS_IP - assumed 'REDIS_IP' (this will throw an Error in a future version of PHP) in /scr1/bitcoin-neo4j/bitcoin-to-neo4j/main.php on line 15
PHP Warning:  Use of undefined constant REDIS_PORT - assumed 'REDIS_PORT' (this will throw an Error in a future version of PHP) in /scr1/bitcoin-neo4j/bitcoin-to-neo4j/main.php on line 15
PHP Warning:  Redis::connect() expects parameter 2 to be integer, string given in /scr1/bitcoin-neo4j/bitcoin-to-neo4j/main.php on line 15
PHP Warning:  Use of undefined constant NEO4J_USER - assumed 'NEO4J_USER' (this will throw an Error in a future version of PHP) in /scr1/bitcoin-neo4j/bitcoin-to-neo4j/main.php on line 23
PHP Warning:  Use of undefined constant NEO4J_PASS - assumed 'NEO4J_PASS' (this will throw an Error in a future version of PHP) in /scr1/bitcoin-neo4j/bitcoin-to-neo4j/main.php on line 23
PHP Warning:  Use of undefined constant NEO4J_IP - assumed 'NEO4J_IP' (this will throw an Error in a future version of PHP) in /scr1/bitcoin-neo4j/bitcoin-to-neo4j/main.php on line 23
PHP Warning:  Use of undefined constant NEO4J_PORT - assumed 'NEO4J_PORT' (this will throw an Error in a future version of PHP) in /scr1/bitcoin-neo4j/bitcoin-to-neo4j/main.php on line 23
PHP Warning:  stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-bolt/src/IO/StreamSocket.php on line 203
PHP Warning:  stream_socket_client(): unable to connect to tcp://://:7687:7687 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-bolt/src/IO/StreamSocket.php on line 203
PHP Fatal error:  Uncaught GraphAware\Bolt\Exception\IOException: Error to connect to the server(0) :  "php_network_getaddresses: getaddrinfo failed: Name or service not known" in /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-bolt/src/IO/StreamSocket.php:207
Stack trace:
#0 /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-bolt/src/IO/StreamSocket.php(245): GraphAware\Bolt\IO\StreamSocket->connect()
#1 /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-bolt/src/Driver.php(133): 
GraphAware\Bolt\IO\StreamSocket->reconnect()
#2 /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-bolt/src/Driver.php(115): GraphAware\Bolt\Driver->handshake()
#3 /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php(192): GraphAware\Bolt\Driver->session()
#4 /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php(109): GraphAware\Neo4j\Client\Connection\Connection->checkSession()
#5 /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-php-client/src/Client.php(67): GraphAware\Neo4j\Client\Connection\Connection->run('CREATE in /scr1/bitcoin-neo4j/vendor/graphaware/neo4j-bolt/src/IO/StreamSocket.php on line 207
```

**Comment by imnotstiller** [comment]
I was missing this `<?php` in the top of the config.php file.
