### ISSUE TITLE
Unsupported operand types: int - string in /var/www/functions/script.php:293

### ISSUE THREAD

**Issue by yellowonblack** [in3rsha/bitcoin-to-neo4j#27]
Hello,

I run the importer for several days and everything worked normally but now it stopped with the following error:

```
Reading /home/user/.bitcoin/blocks/blk00111.dat...

 1: 00000000000000000888b3c9ac26b034e38d26396d4421f4a190e61e537870d9 [366.35 kb] (fp:70435685) 
......

PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int - string in /var/www/functions/script.php:293
Stack trace:
#0 /var/www/functions/tx.php(91): decodeScript()
#1 /var/www/cyphertx.php(13): decoderawtransaction()
#2 /var/www/main.php(380): cypherTx()
#3 {main}
  thrown in /var/www/functions/script.php on line 293
```

For me it stopped at blk00011.dat  and redis stored info are:

> redis-cli HGETALL bitcoin-to-neo4j
> 1) "blk.dat"
> 2) "111"
> 3) "fp"
> 4) "70435685"

> redis-cli HGETALL bitcoin-to-neo4j:tip
> 1) "height"
> 2) "283110"
> 3) "hash"
> 4) "000000000000000167b56449edc301a97e499dcae29b20edcf106f194a4ba939"

I don't know if blk*.dat files are identical between installations but I may provide the one which cause the issue. 

I'm running the script main.php in a docker container, but I don't know if that is relevant, as it worked fine until this error.

Thanks.

**Comment by Jerry602071349** [comment]
I encounter the same issue; any solution would be appreciated.
